### ISSUE TITLE
Качество кода хромает сильно 

### ISSUE THREAD

**Issue by rengoyli** [0xc0000007b/crap-game#1]

**Comment by rengoyli** [comment]
Какие советы дашь?

**Comment by 0xc0000007b** [comment]
> Какие советы дашь?

относительно чего?

**Comment by rengoyli** [comment]
> относительно чего?

Кода. Что там не так?

**Comment by rengoyli** [comment]
> > Какие советы дашь?
> 
> относительно чего?

Эаххахххазахвзазахащадхвх
я думал это ты открыл ишшю в мой репо xD
